CREATE TABLE IF NOT EXISTS tenants (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name text NOT NULL);
CREATE TABLE IF NOT EXISTS channels (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), platform text NOT NULL, external_account_id text NOT NULL, is_healthy boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS contacts (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), platform text NOT NULL, external_account_id text NOT NULL, external_customer_id text NOT NULL, display_name text NOT NULL, phone text NOT NULL, UNIQUE (tenant_id, platform, external_account_id, external_customer_id));
CREATE TABLE IF NOT EXISTS conversations (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), channel_id uuid NOT NULL REFERENCES channels(id), contact_id uuid NOT NULL REFERENCES contacts(id), status text NOT NULL, updated_at timestamptz NOT NULL, last_read_sequence bigint NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id uuid NOT NULL REFERENCES conversations(id), direction text NOT NULL, body text NOT NULL, external_message_id text, status text NOT NULL, created_at timestamptz NOT NULL, sequence bigint NOT NULL, UNIQUE (tenant_id, conversation_id, sequence), UNIQUE (tenant_id, external_message_id));
CREATE TABLE IF NOT EXISTS internal_notes (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), conversation_id uuid NOT NULL REFERENCES conversations(id), author_id uuid NOT NULL, body text NOT NULL, created_at timestamptz NOT NULL, sequence bigint NOT NULL, UNIQUE (tenant_id, conversation_id, sequence));
CREATE TABLE IF NOT EXISTS outbox_events (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), type text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL, dispatched_at timestamptz);
CREATE TABLE IF NOT EXISTS webhook_receipts (id uuid PRIMARY KEY, channel_id uuid NOT NULL REFERENCES channels(id), provider_event_id text NOT NULL, raw_body bytea NOT NULL, received_at timestamptz NOT NULL, UNIQUE (channel_id, provider_event_id));
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE internal_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_conversations ON conversations USING (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_messages ON messages USING (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_notes ON internal_notes USING (tenant_id = current_setting('app.tenant_id', true)::uuid);
