import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { normalizeActivity } from './api/activity';

type Conversation = { id: string; contactName: string; platform: string; preview: string; status: string; unread: boolean };
type Activity = { kind: 'Message' | 'InternalNote'; body: string; direction?: string; createdAt: string };
const api = async (path: string, init: RequestInit = {}) => fetch(`/api/v1${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) } }).then(async r => { if (!r.ok) throw new Error(await r.text()); return r.json(); });

function Login({ onLogin }: { onLogin: (token: string) => void }) { const [form, setForm] = useState({ tenantSlug: 'acme', email: 'agent@acme.test', password: 'demo' }); const submit = async (e: React.FormEvent) => { e.preventDefault(); const result = await api('/auth/login', { method: 'POST', body: JSON.stringify(form) }); onLogin(result.accessToken); }; return <main className="login"><form onSubmit={submit}><p className="eyebrow">UNIFIED INBOX</p><h1>Welcome back</h1><label>Workspace slug<input value={form.tenantSlug} onChange={e => setForm({ ...form, tenantSlug: e.target.value })} /></label><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button>Open inbox</button><small>Demo workspace: acme · agent@acme.test</small></form></main>; }
function Inbox({ token }: { token: string }) { const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<string>(); const [activity, setActivity] = useState<Activity[]>([]); const [draft, setDraft] = useState(''); useEffect(() => { api('/conversations', { headers: { Authorization: `Bearer ${token}` } }).then((items: Conversation[]) => { setConversations(items); if (items[0]) setSelected(items[0].id); }); }, [token]); useEffect(() => { if (selected) api(`/conversations/${selected}/activity`, { headers: { Authorization: `Bearer ${token}` } }).then(payload => setActivity(normalizeActivity<Activity>(payload))); }, [selected, token]); const send = async () => { if (!selected || !draft.trim()) return; await api(`/conversations/${selected}/messages`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ body: draft }) }); setDraft(''); const payload = await api(`/conversations/${selected}/activity`, { headers: { Authorization: `Bearer ${token}` } }); setActivity(normalizeActivity<Activity>(payload)); }; return <main className="app"><header><div><p className="eyebrow">ACME WORKSPACE</p><h1>Shared inbox</h1></div><span className="health"><i /> WhatsApp connected</span></header><section className="layout"><aside className="list"><input aria-label="Search conversations" placeholder="Search conversations" /><div className="filters"><button>Open</button><button>Unread</button><button>Closed</button></div>{conversations.map(c => <button className={`conversation ${selected === c.id ? 'selected' : ''}`} key={c.id} onClick={() => setSelected(c.id)}><span className="avatar">{c.contactName[0]}</span><span><strong>{c.contactName}</strong><small>{c.preview}</small></span>{c.unread && <b>•</b>}</button>)}</aside><section className="thread">{selected ? <><div className="thread-head"><div><strong>{conversations.find(c => c.id === selected)?.contactName}</strong><small>WhatsApp · customer-1</small></div><button>Mark closed</button></div><div className="timeline">{[...activity].reverse().map((item, i) => <article className={item.kind === 'InternalNote' ? 'note' : ''} key={`${item.createdAt}-${i}`}><small>{item.kind === 'InternalNote' ? 'Internal note' : 'Message'}</small><p>{item.body}</p></article>)}</div><div className="composer"><textarea aria-label="Message" value={draft} onChange={e => setDraft(e.target.value)} placeholder="Write a reply…" /><div><button className="ghost">Add note</button><button onClick={send}>Send message</button></div></div></> : <div className="empty">Select a conversation to get started.</div>}</section><aside className="profile"><p className="eyebrow">CUSTOMER</p><h2>Jamie Customer</h2><p>+1 555 000 0001</p><hr /><p className="eyebrow">CHANNEL</p><p>WhatsApp<br />business-acme</p></aside></section></main>; }
function App() { const [token, setToken] = useState<string | null>(null); return token ? <Inbox token={token} /> : <Login onLogin={setToken} />; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
